"""pipeline restart requeue count

Revision ID: 1903c9ed442e
Revises: d7e3f1a2b4c5
Create Date: 2026-10-07 21:41:37.378480

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1903c9ed442e"
down_revision = "d7e3f1a2b4c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("processing_job", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "restart_requeues", sa.Integer(), server_default="0", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("processing_job", schema=None) as batch_op:
        batch_op.drop_column("restart_requeues")

    # ### end Alembic commands ###
